package enums

enum QuestionType {
    ENTITY_QUESTIONAIRE,
    SIMPLE_ANAGRAM,
    UNSOLVABLE_ANAGRAM_STUDY1,
    UNSOLVABLE_ANAGRAM_STUDY2,
    ADAPTATION_SCALE_STUDY1_PARTA,
    ADAPTATION_SCALE_STUDY1_PARTB
}